// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcredis.proto

package io.grpc.examples.grpcredis;

public interface MGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcredis.MGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string keys = 1;</code>
   */
  java.util.List<java.lang.String>
      getKeysList();
  /**
   * <code>repeated string keys = 1;</code>
   */
  int getKeysCount();
  /**
   * <code>repeated string keys = 1;</code>
   */
  java.lang.String getKeys(int index);
  /**
   * <code>repeated string keys = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);
}
